name: "Terraform Validate"

on:
    pull_request:
      branches:
        - main

jobs:
  terraform:
    name: "Terraform Format and Validate"
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: "Checkout code"
        uses: actions/checkout@v3

      # Set up Terraform
      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7

      # Initialize Terraform
      - name: "Terraform Init"
        id: init
        run: terraform init

      # Format Terraform files recursively
      - name: "Terraform Format Check"
        id: fmt
        run: terraform fmt -check -recursive

      # Validate Terraform configuration
      - name: "Terraform Validate"
        id: validate
        run: terraform validate
